---
name: Build Bottles

"on":
  workflow_run:
    workflows: ["Hatari+HRDB Bundle Test Formula"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build bottles for'
        required: false
        default: 'stable'
        type: choice
        options:
          - stable
          - head

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  check-tests:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_dispatch'
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Check if we should build
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event.workflow_run.conclusion }}" == \
                  "success" ]]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          fi

  build-bottles:
    needs: check-tests
    if: needs.check-tests.outputs.should_build == 'true'
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-15-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: |
          brew tap ${{ github.repository }}
          brew install --only-dependencies hatari-hrdb

      - name: Build bottle
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && \
                "${{ github.event.inputs.version }}" == "head" ]]; then
            brew install --build-bottle --HEAD hatari-hrdb
            brew bottle --no-rebuild hatari-hrdb --json
          else
            brew install --build-bottle hatari-hrdb
            brew bottle --no-rebuild hatari-hrdb --json
          fi

      - name: Upload bottle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.arch }}
          path: |
            *.bottle.tar.gz
            *.bottle.json
          retention-days: 30

  create-release:
    needs: build-bottles
    if: needs.check-tests.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          path: bottles/

      - name: Generate release tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && \
                "${{ github.event.inputs.version }}" == "head" ]]; then
            COMMIT_HASH=$(cd $(brew --cache)/downloads && find . -name "hatari-*" -type d | head -1 | xargs -I {} git -C {} rev-parse --short HEAD 2>/dev/null || echo "head")
            TAG="bottles-head-${COMMIT_HASH}-$(date +%Y%m%d-%H%M%S)"
          else
            VERSION=$(brew list --versions hatari-hrdb | cut -d' ' -f2)
            TAG="bottles-${VERSION}-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "Bottles ${{ steps.tag.outputs.tag }}"
          body: |
            Pre-built bottles for hatari-hrdb

            **Installation:**
            ```bash
            brew tap kareandersen/homebrew-hatari-hrdb
            brew install hatari-hrdb
            ```
          files: |
            bottles/bottles-arm64/*.bottle.tar.gz
            bottles/bottles-arm64/*.bottle.json
            bottles/bottles-x86_64/*.bottle.tar.gz
            bottles/bottles-x86_64/*.bottle.json
          draft: false
          prerelease: ${{ github.event.inputs.version == 'head' }}
